### ISSUE TITLE
TagField doesn't render in AssetAdmin

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-tagfield#107]
Trying to add a `TagField` to `Image` and get an empty dropdown and no ability to add new tags. I imagine that React is getting in the way - happy to take a crack at it but have no idea what direction to go in.

To reproduce:

```php
class GalleryImageExtension extends DataExtension
{
    private static $many_many = [
        'GalleryImageTags' => GalleryImageTag::class,
    ];
}
```

```php
class GalleryImageFormFactoryExtension extends Extension
{
    public function updateFormFields(FieldList $fields, $controller, $formName, $context)
    {
        $image = $context['Record'];
        $tagField = TagField::create(
            'GalleryImageTags',
            'Tags',
            GalleryImageTag::get(),
            $image->GalleryImageTags()
        );
        $fields->addFieldToTab('Editor.Details', $tagField);
    }
}
```

```php
class GalleryImageTag extends DataObject
{
    private static $db = [
        'Title' => 'Varchar(50)',
    ];

    private static $belongs_many_many = [
        'GalleryImages' => Image::class,
    ];

    private static $table_name = 'GalleryImageTag';
}
```

```yml
SilverStripe\Assets\Image:
  extensions:
    - 'GalleryImageExtension'
SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - 'GalleryImageFormFactoryExtension'
```
